; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName={cm:MyAppName}
AppVerName={cm:MyAppName} V5
DefaultDirName={reg:HKCU\Software\Astro_PC\VirtualMoon,Install_Dir|{commonpf32}\VirtualMoon}
InfoBeforeFile=setup_pict\readme.txt
OutputDir=.\
OutputBaseFilename=virtualmoon-picture
Compression=zip
SolidCompression=true
UseSetupLdr=true
UsePreviousAppDir=false
WizardImageFile=setup_pict\WizMoonImage.bmp
WizardSmallImageFile=setup_pict\WizMoonSmallImage.bmp
UninstallLogMode=append
AppID={{3EB7A19B-690F-49BA-B494-CADA547D0DB9}
CreateUninstallRegKey=false
UpdateUninstallLogAppName=false
DirExistsWarning=no
ShowLanguageDialog=yes
UsedUserAreasWarning=no

[Languages]
Name: eng; MessagesFile: compiler:Default.isl; InfoBeforeFile: setup_pict\readme.txt
Name: fre; MessagesFile: compiler:Languages\French.isl; InfoBeforeFile: setup_pict\lisezmoi.txt

[InstallDelete]
Name: {app}\BestOfAmateurs\*.jpg; Type: files
Name: {app}\BestOfHiggins\*.jpg; Type: files
Name: {app}\BestOfLazzarotti\*.jpg; Type: files
Name: {app}\BestOfCathala\*.jpg; Type: files
Name: {app}\Best_of_Peach\*.jpg; Type: files
Name: {app}\Best_Pic_du_Midi\*.jpg; Type: files
Name: {app}\BestOfBrahic\*.jpg; Type: files
Name: {app}\BestOfViladrich\*.jpg; Type: files
Name: {app}\BestofPelissard\*.jpg; Type: files
Name: {app}\BestOfHeully\*.jpg; Type: files

[Messages]
eng.UninstalledAll=%1 was successfully removed from your computer.
fre.UninstalledAll=%1 a été correctement désinstallé de cet ordinateur.

[CustomMessages]
eng.MyAppName=VMA additional picture library
fre.MyAppName=AVL bibliothèques d'image complémentaires

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: vmapro\Data\*; DestDir: {app}; Flags: recursesubdirs ignoreversion replacesameversion createallsubdirs 

[_ISTool]
UseAbsolutePaths=false
